### ISSUE TITLE
xrange fails to overflow?

### ISSUE THREAD

**Issue by mt-caret** [bialix/intelhex#14]
Running the tests gives me

```
======================================================================            
FAIL: test_xrange_longint (intelhex.test.TestXrangeLongInt)                       
----------------------------------------------------------------------            
Traceback (most recent call last):       
  File "/tmp/nix-build-python2.7-intelhex-2.1.drv-0/intelhex-2.1/intelhex/test.py", line 1601, in test_xrange_longint
    self.assertRaises(OverflowError, xrange, 2684625744, 2684625747)              
AssertionError: OverflowError not raised 

----------------------------------------------------------------------
```

trying something similar in a python interpreter gives the same results:

```
$ python                                                                       
Python 2.7.13 (default, Dec 17 2016, 20:05:07)                                                                
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> xrange(2684625744, 2684625747)                                                                            
xrange(2684625744, 2684625747)                                                                                
```

while something like this does in fact throw an OverflowError:

```
>>> xrange(2684625744, 2**100)                                                                                
Traceback (most recent call last):                                                                            
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

**Comment by bialix** [comment]
Thank you for reporting this.

This error is harmless, and only indicates that my assumptions about xrange behavior is not quite correct on your system. I'd suspect that's due 64-bit platform, but on with Windows build of Python 2.7.13 - I still get OverflowError with my original statement.

Can you check on your python what's the result of the following expression:

`type(2684625744)
`

**Comment by mt-caret** [comment]
```
$ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> type(2684625744)
<type 'int'>
```

Looks like I start getting 'long's from 1 << 63:

```
$ python                                                                                                
Python 2.7.13 (default, Dec 17 2016, 20:05:07)                                                                       
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> type(1<<32)                                                                                                      
<type 'int'>                                                                                                         
>>> type(1<<62)                                                                                                      
<type 'int'>                                                                                                         
>>> type(1<<63)                                                                                                      
<type 'long'>                                                                                                        
>>>
```
My machine is running on Linux x86_64 (NixOS), if that helps

**Comment by bialix** [comment]
Yes, my guess about your system was right. I suppose that's somehow related to your compiler and/or OS system libs.

I can only put additional check in the tests to skip tests if type(1<<32) is not long.

Would you like to provide a patch?
