### ISSUE TITLE
hex2bin error

### ISSUE THREAD

**Issue by kript0n** [bialix/intelhex#4]
Hey. I tried use hex2bin function im my code then tried your script and all the time I get this error:
`Traceback (most recent call last):
  File "hex2.py", line 139, in <module>
    sys.exit(hex2bin(fin, fout, start, end, size, pad))
  File "/usr/local/lib/python3.4/dist-packages/intelhex/__init__.py", line 1001, in hex2bin
    h.tobinfile(fout, start, end)
  File "/usr/local/lib/python3.4/dist-packages/intelhex/__init__.py", line 412, in tobinfile
    fobj.write(self._tobinstr_really(start, end, pad, size))
TypeError: must be str, not bytes
` 
Script I use as `python3 hex2bin Blinky.hex`

**Comment by bialix** [comment]
Hello, it seems there is indeed bug in python3 version. Usually you have to provide output bin filename as last parameter, after filename of input hex file. Without output filename my script tries to write binary data to stdout and that provoked error.

As workaround try to run command with output filename argument:

python3 hex2bin Blinky.hex Blinky.bin

**Comment by bialix** [comment]
According to http://stackoverflow.com/a/908440 IntelHex on Python3 should use `sys.stdout.buffer.write` to write binary data to stdout.
